// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj7AhDQabL97nxfvYIWpUMF2OF6iJv6cg',
    appId: '1:132281427539:web:cedc170de0f753169448a6',
    messagingSenderId: '132281427539',
    projectId: 'flutterauth-b22bc',
    authDomain: 'flutterauth-b22bc.firebaseapp.com',
    storageBucket: 'flutterauth-b22bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACzV98YhqU3dQiC75bQks6_wwhWM5lUPA',
    appId: '1:132281427539:android:4c80f5601976d8d79448a6',
    messagingSenderId: '132281427539',
    projectId: 'flutterauth-b22bc',
    storageBucket: 'flutterauth-b22bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa7lzj2JDKCl-DKWtdvzc4b57yPOAXIqs',
    appId: '1:132281427539:ios:3da938bb3e15b54c9448a6',
    messagingSenderId: '132281427539',
    projectId: 'flutterauth-b22bc',
    storageBucket: 'flutterauth-b22bc.appspot.com',
    iosBundleId: 'com.example.mobileApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa7lzj2JDKCl-DKWtdvzc4b57yPOAXIqs',
    appId: '1:132281427539:ios:11bea3e84b4065859448a6',
    messagingSenderId: '132281427539',
    projectId: 'flutterauth-b22bc',
    storageBucket: 'flutterauth-b22bc.appspot.com',
    iosBundleId: 'com.example.mobileApplication.RunnerTests',
  );
}
